# Generated by Django 3.2 on 2021-04-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_relationnurse_relationpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationpatient',
            name='patient',
        ),
        migrations.AddField(
            model_name='nurse',
            name='patients',
            field=models.ManyToManyField(to='accounts.Patient'),
        ),
        migrations.DeleteModel(
            name='RelationNurse',
        ),
        migrations.DeleteModel(
            name='RelationPatient',
        ),
    ]
