# Generated by Django 3.2 on 2021-04-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210416_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
