# Generated by Django 3.2 on 2021-04-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pain_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pain',
        ),
    ]
