# Generated by Django 3.2 on 2021-04-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_pain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
