# Generated by Django 3.2 on 2021-04-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pain_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pain',
        ),
    ]
