# Generated by Django 3.2 on 2021-04-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pain',
            name='name',
        ),
    ]
