# Generated by Django 3.2 on 2021-04-18 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_pain_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage', models.CharField(max_length=200, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('time1', models.TimeField(null=True)),
                ('time2', models.TimeField(null=True)),
                ('time3', models.TimeField(null=True)),
                ('time4', models.TimeField(null=True)),
                ('time5', models.TimeField(null=True)),
                ('time6', models.TimeField(null=True)),
                ('time7', models.TimeField(null=True)),
                ('time8', models.TimeField(null=True)),
                ('medications', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medication')),
                ('patients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
            ],
        ),
    ]
