# Generated by Django 3.2 on 2021-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_medication_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time6',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time7',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time8',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
