# Generated by Django 3.2 on 2021-04-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210420_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
