# Generated by Django 3.2 on 2021-07-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210620_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
