# Generated by Django 3.2 on 2021-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210718_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
