# Generated by Django 3.2 on 2021-07-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210718_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
